version: '3'
services:

  #PHP Service
  dig-php:
    build:
      context: .
      dockerfile: docker/services/php/Dockerfile
    image: superrosko/php:7.4-fpm
    container_name: dig-php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: dig-php
      SERVICE_TAGS: dev
    networks:
      - internal

  #App Service
  dig-app:
    build:
      context: .
      dockerfile: docker/services/app/Dockerfile
    image: superrosko/dig
    container_name: dig-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: dig-app
      SERVICE_TAGS: dev
      XDEBUG_CONFIG: $XDEBUG_CONFIG
      PHP_IDE_CONFIG: serverName=dig.localhost
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/services/app/conf/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/services/app/conf/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - internal
    depends_on:
      - dig-php

#Docker Networks
networks:
  internal:
    driver: bridge
